const std = @import("std");

pub fn build(b: *std.Build) void {
    // --- 1. BACK TO PURE BARE-METAL ---
    const target = b.resolveTargetQuery(.{
        .cpu_arch = .riscv32,
        .os_tag = .freestanding, // Must be freestanding!
        .abi = .none,
        .cpu_model = .{ .explicit = &std.Target.riscv.cpu.generic_rv32 },
        .cpu_features_add = std.Target.riscv.featureSet(&[_]std.Target.riscv.Feature{ .m, .c }),
    });

    const lib = b.addLibrary(.{
        .linkage = .static,
        .name = "zig_app",
        .root_module = b.createModule(.{
            .root_source_file = b.path("main/app.zig"),
            .target = target,
            .optimize = .ReleaseSmall,
        }),
    });

    lib.root_module.addCMacro("ESP_PLATFORM", "1");

    // --- 2. SCRAPE CMAKE'S BRAIN ---
    scrapeCmakePaths(b, lib);

    b.installArtifact(lib);
}

// ====================================================================
// THE MAGIC: Parse compile_commands.json
// ====================================================================
fn scrapeCmakePaths(b: *std.Build, lib: *std.Build.Step.Compile) void {
    // Open the compile_commands.json file generated by ESP-IDF
    const file_contents = std.fs.cwd().readFileAlloc(b.allocator, "build/compile_commands.json", 1024 * 1024 * 50) catch |err| {
        std.debug.print("WARNING: Could not read compile_commands.json ({}). Run 'idf.py reconfigure' first!\n", .{err});
        return;
    };

    // We use a brutal but extremely fast string tokenizer to extract the paths.
    // It splits the JSON file by spaces, quotes, and newlines to isolate the compiler flags.
    var it = std.mem.tokenizeAny(u8, file_contents, " \n\r\t\\\"");

    // Use a StringHashMap to ensure we don't add duplicate paths and slow down the compiler
    var seen_paths = std.StringHashMap(void).init(b.allocator);
    defer seen_paths.deinit();

    while (it.next()) |token| {
        // Find standard includes (-I/path/to/folder)
        if (std.mem.startsWith(u8, token, "-I") and token.len > 2) {
            const path = token[2..];
            if (!seen_paths.contains(path)) {
                seen_paths.put(path, {}) catch continue;
                lib.addIncludePath(.{ .cwd_relative = path });
            }
        }
        // Find system includes (-isystem /path/to/folder)
        else if (std.mem.eql(u8, token, "-isystem")) {
            if (it.next()) |sys_path| {
                if (!seen_paths.contains(sys_path)) {
                    seen_paths.put(sys_path, {}) catch continue;
                    lib.addSystemIncludePath(.{ .cwd_relative = sys_path });
                }
            }
        }
    }
}
